### ISSUE TITLE
Webhookinterceptor blows up with missing milestone

### ISSUE THREAD

**Issue by andreasohlund** [ParticularTools/ITOps#3]
2015-06-23 09:22:42.133 +00:00 [Error] Unhandled error on request "http://automation.particular.net/WebHookInterceptor/github"
System.NullReferenceException: Object reference not set to an instance of an object.
   at ITOps.Hosts.WebHookInterceptor.GitHub.MilestoneConverer.Convert(MilestoneDto milestoneDto) in c:\BuildAgent\work\f25429a40230ca10\src\ITOps.Hosts.WebHookInterceptor\GitHub\MilestoneConverer.cs:line 10
   at ITOps.Hosts.WebHookInterceptor.GitHub.Issues.IssuesEventHandler.<Handle>d__4.MoveNext() in c:\BuildAgent\work\f25429a40230ca10\src\ITOps.Hosts.WebHookInterceptor\GitHub\Issues\IssuesEventHandler.cs:line 26
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at ITOps.Hosts.WebHookInterceptor.WebHookPayloadHandlerExecutor.Handle(Object payload) in c:\BuildAgent\work\f25429a40230ca10\src\ITOps.Hosts.WebHookInterceptor\WebHookPayloadHandlerExecutor.cs:line 25
   at ITOps.Hosts.WebHookInterceptor.GitHubWebHookHandler.<>c__DisplayClass2.<.ctor>b__0(Object _) in c:\BuildAgent\work\f25429a40230ca10\src\ITOps.Hosts.WebHookInterceptor\GitHubWebHookHandler.cs:line 28
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

**Comment by andreasohlund** [comment]
Payload: https://github.com/organizations/Particular/settings/hooks/4914031
